export const items = [
  "Carbon Based Lifeforms",
  "Cell",
  "Aes Dana",
  "Connect.Ohm",
  "Sync24",
  "H.U.V.A. Network",
  "Solar Fields",
  "Asura",
  "Scann-Tec",
  "Lauge",
  "Miktek",
  "Astropilot",
  "Vibrasphere",
  "Hol Baumann",
  "Lab's Cloud",
  "Entheogenic",
  "Between Interval",
  "SiebZehN",
  "I Awake",
  "Sundial Aeon",
  "Tripswitch",
  "Martin Nonstatic",
  "State Azure",
  "Ascendant",
  "Astronaut Ape",
  "Suduaya",
  "Koan",
  "Zero Cult",
  "Abakus",
  "James Murray",
  "Chronos",
  "Circular",
  "Ott",
  "Mystical Sun",
  "Hinkstep",
  "Bluetech",
  "Shpongle",
  "Eguana",
  "Cygna",
  "Dreaming Cooper",
  "Yagya",
  "Dhamika",
  "Biosphere",
  "Side Liner",
  "David Helpling",
  "36",
  "Aural Planet",
  "M-Seven",
  "Shulman",
  "Younger Brother",
  "Androcell",
  "Germind",
  "Solar Quest",
  "Unusual Cosmic Process",
  "Mystic Crock",
  "Perpetual Loop",
  "Lars Leonhard",
  "All India Radio",
  "Easily Embarrassed",
  "Kaya Project",
  "Zymosis",
  "Jonn Serrie",
  "Desert Dwellers",
  "Kliment",
  "nigel stanford",
  "Helios",
  "Maluns",
  "ISHQ",
  "Sensorica",
  "One Arc Degree",
  "Kuba",
  "Joey Fehrenbach",
  "Kick Bong",
  "The Future Sound of London",
  "Cosmic Replicant",
  "Man Of No Ego",
  "Erot",
  "Hammock",
  "Dreamstate Logic",
  "Jon Hopkins",
  "Ulrich Schnauss",
  "Global Communication",
  "Sysyphe",
  "Robert Rich",
  "Lights Out Asia",
  "Warmth",
  "Subheim",
  "Sounds from the Ground",
  "Banco De Gaia",
  "Jani R",
  "Lauge & Baba Gnohm",
  "Cabeiri",
  "Loscil",
  "Oleg Byonic",
  "Hibernation",
  "Steve Hauschildt",
  "Dense",
  "The Orb",
  "Galaxy",
  "AmBeam",
  "Saafi Brothers",
  "Puff Dragon",
  "Phutureprimitive",
  "Rudy Adrian",
  "Krusseldorf",
  "Bvdub",
  "Floex",
  "Steve Roach",
  "Jens Buchert",
  "Solarsoul",
  "Ulrich Schnauss & Jonas Munk",
  "En Voice",
  "Master Margherita",
  "Schiller",
  "Blut Own",
  "Emancipator",
  "Delerium",
  "Tycho",
  "Seamoon",
  "SVLBRD",
  "Ishome",
  "Abul Mogard",
  "Zen Baboon",
  "Thomas Lemmer",
  "Bersarin Quartett",
  "Jon Jenkins",
  "Rautu",
  "Adham Shaikh",
  "Bliss",
  "Motionfield",
  "Conjure One",
  "Thom Brennan",
  "Martin Stig Andersen",
  "Marconi Union",
  "Amethystium",
  "Vasily Dvortsov",
  "Boards of Canada",
  "William Orbit",
  "Rhian Sheehan",
  "Liam Thomas",
  "Telefon Tel Aviv",
  "Ingo Herrmann",
  "Kalya Scintilla",
  "Aljosha Konstanty",
  "Hiatus",
  "Ambient",
  "Röyksopp",
  "Jean Michel Jarre",
  "Adam Fielding",
  "Field Rotation",
  "Gidge",
  "Tosca",
  "Lemongrass",
  "Alessandro Cortini",
  "Ocoeur",
  "Phaeleh",
  "Secede",
  "Elea",
  "Woob",
  "Jaia",
  "Orbital",
  "Eastern Sun",
  "Moby",
  "Erik Wøllo",
  "Michael FK",
  "Kodomo",
  "Enigma",
  "Markus Guentner",
  "Klangstein",
  "Rocket Empire",
  "Tony Anderson",
  "Tineidae",
  "Seven24",
  "Michael McCann",
  "Flooting Grooves",
  "S1gns Of L1fe",
  "Bryan El",
  "Spacetime Continuum",
  "The Black Dog",
  "Monolake",
  "Gas",
  "Bonobo",
  "Deep Forest",
  "Tangerine Dream",
  "Max Corbacho",
  "Hybrid Leisureland",
  "Tipper",
  "Rafael Anton Irisarri",
  "Globular",
  "Gaudi",
  "Craig Padilla",
  "The Sight Below",
  "Max Million",
  "Kaminanda",
  "Tentura",
  "Эдуард Артемьев",
  "RealX",
  "Susumu Yokota",
  "Stefan Torto",
  "Klaus Schulze",
  "The Irresistible Force",
  "Nale",
  "zarr.",
  "Tor",
  "Eskadet",
  "The American Dollar",
  "Lama House",
  "Arovane",
  "Michael Stearns",
  "Cliff Martinez",
  "Hecq",
  "Landhouse",
  "Amorphous Androgynous",
  "Trifonic",
  "The Infinity Project",
  "Purl",
  "Thievery Corporation",
  "Chicane",
  "Blank & Jones",
  "Jon Kennedy",
  "Binaural Beats",
  "Murcof",
  "Proem",
  "Pete Namlook",
  "Fila Brazillia",
  "The Ambientalist",
  "Ambyion",
  "nor elle",
  "Nikonn",
  "Lusine",
  "Phil France",
  "Apparat",
  "Hollan Holmes",
  "Julian Kruse",
  "El LCD",
  "Puremusic",
  "Ascent & Argus",
  "Reasonandu",
  "stereOMantra",
  "I.M.D",
  "R.I.B.",
  "Airform",
  "AES DANA feat. MIKTEK",
  "Aythar",
  "profondita",
  "MER-A",
  "Neuroq",
  "LAUGE & AES DANA",
  "subdream",
  "EskoStatic",
  "Rukirek",
];
